[package]
name = "gwt"
version = "0.1.0"
edition = "2024"

[dependencies]
parser = {path="../parser/"}
clap = { version = "4.5", features = ["derive"] }
miette = { version = "7.5", features = ["fancy"] }
